console.log(challenge) 
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substring(3))
console.log(challenge.substring(0,2))
console.log(challenge.includes('Script'))
console.log(company)
console.log(companyArray)
console.log(challenge.replace('JavaScript', 'Python'))
console.log(challenge.charAt(15))
console.log(challenge.charCodeAt('J'))
console.log(challenge.indexOf('a'))
console.log(challenge.lastIndexOf('a'))
console.log(cause.indexOf('because'))
console.log(cause.lastIndexOf('because'))
console.log(cause.search('because'))
console.log(challenge.trim())
console.log(challenge.startsWith('30'))
console.log(challenge.endsWith('JavaScript'))
console.log(challenge.match('a'))
console.log(firstPart.concat(' ', secondPart))
console.log(challenge.repeat(2))